[package]
authors = ["Programatik <programatik29@gmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server designed to be used with axum framework."
edition = "2018"
homepage = "https://github.com/programatik29/axum-server"
keywords = ["http", "https", "web", "server"]
license = "MIT"
name = "axum-server"
readme = "README.md"
repository = "https://github.com/programatik29/axum-server"
version = "0.3.2"

[features]
default = []
tls-rustls = ["arc-swap", "pin-project-lite", "rustls", "rustls-pemfile", "tokio/fs", "tokio-rustls"]

[dependencies]
bytes = "1"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
http = "0.2"
http-body = "0.4"
hyper = { version = "0.14.15", features = ["http1", "http2", "server", "runtime"] }
tokio = { version = "1", features = ["macros", "net", "sync"] }
tower-service = "0.3"

# optional dependencies
arc-swap = { version = "1", optional = true }
pin-project-lite = { version = "0.2", optional = true }
rustls = { version = "0.20", features = ["dangerous_configuration"], optional = true }
rustls-pemfile = { version = "0.2", optional = true }
tokio-rustls = { version = "0.23", optional = true }

[dev-dependencies]
axum = "0.3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util"] }

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "http_and_https"
required-features = ["tls-rustls"]

[[example]]
name = "rustls_reload"
required-features = ["tls-rustls"]

[[example]]
name = "rustls_server"
required-features = ["tls-rustls"]
